package br.com.fiap.namastreta.models;

public enum Categoria {
    LOUCURAS_ABSTRATAS,
    MUNDO_SURREAL,
    CORES_VIBRANTES,
    EXPRESSOES_FANTASTICAS,
    FICCAO_CIENTIFICA_VISUAL,
    SONHOS_EM_TINTA,
    IMAGINACAO_DESENFREADA,
    DIVERSAO_CRIATIVA,
    REALIDADE_ALTERNATIVA,
    CAOS_ARTISTICO
}
